// packages/react-native-backup-with-portabl/src/index.tsx
import React, { useEffect, useMemo, useState } from 'react';
import {
  Options,
  ATTRIBUTES,
  createOnboardingUrl,
} from '@portabl/backup-common';
import { Pressable, Image, View, Linking } from 'react-native';
import { styles } from './styles';

const BackupWithPortabl = ({
  redirectUri,
  prepareBackup,
  loadBackupData,
  local = null,
}: Options) => {
  const [accessToken, setAccessToken] = useState<string | null>();

  useEffect(() => {
    if (!accessToken) {
      (async () => {
        const data = await prepareBackup();
        setAccessToken(data.accessToken);
      })();
    }
  }, [accessToken]);

  const url = useMemo(
    () =>
      accessToken
        ? createOnboardingUrl({ accessToken, redirectUri, local })
        : '',
    [accessToken, redirectUri, local],
  );

  const handleButtonClick = async () => {
    if (accessToken) {
      loadBackupData({ accessToken });
      await Linking.openURL(url);
    }
  };

  if (url) {
    return (
      <Pressable
        onPress={handleButtonClick}
        style={({ pressed }) => [
          pressed ? styles.buttonPressed : styles.button,
        ]}
      >
        {({ pressed }) => (
          <View style={styles.buttonContentWrapper}>
            <Image
              style={styles.connectImage}
              source={{
                uri: pressed
                  ? ATTRIBUTES.imagePressed
                  : ATTRIBUTES.imageDefault,
              }}
            />
          </View>
        )}
      </Pressable>
    );
  }

  return null;
};

export default BackupWithPortabl;

// packages/vue-backup-with-portabl/src/index.vue
<script setup lang="ts">
import { watchEffect, reactive, watch } from 'vue';
import {
  ATTRIBUTES,
  createOnboardingUrl,
  ROOT_ELEMENT_ID,
  styles,
} from '@portabl/backup-common';

const props = defineProps<{
  prepareBackup: () => Promise<{ accessToken: string }>;
  loadBackupData: ({ accessToken }: { accessToken: string }) => void;
  redirectUri: string;
  local?: string;
}>();

const state = reactive({
  accessToken: '',
  url: '',
});

watchEffect(() => {
  if (!state.accessToken) {
    (async () => {
      const data = await props.prepareBackup();
      state.accessToken = data.accessToken;
    })();
  }
});

watch(
  () => state.accessToken,
  accessToken => {
    const createOnboardingUrlData = {
      accessToken,
      redirectUri: props.redirectUri,
      local: props.local,
    };
    state.url = accessToken ? createOnboardingUrl(createOnboardingUrlData) : '';
  },
);

const handleButtonClick = async () => {
  if (state.accessToken) {
    props.loadBackupData({
      accessToken: state.accessToken,
    });
  }
};
</script>

<template>
  <div :class="styles['portabl-backup-root']" :id="ROOT_ELEMENT_ID">
    <a
      v-if="state.url"
      :href="state.url"
      target="_blank"
      rel="noreferrer"
      role="button"
      @click="handleButtonClick"
    >
      <div
        :class="ATTRIBUTES.imageWrapperClassName"
        role="img"
        :aria-label="ATTRIBUTES.ariaLabel"
      />
    </a>
  </div>
</template>
